name: Filebeat v7 - Scan Latest Image

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  "10 16 * * *"

defaults:
  run:
    working-directory: ./v7

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/filebeat

jobs:

  scan:
    name: Weekly Scan of Latest v7 Tag
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Set Variables
        run: |
          VER=$(cat filebeat.target.version)
          echo "FILEBEAT_VERSION=$VER" >> $GITHUB_ENV
          LATEST_TAG=$(git tag -l "7.*" --sort=-taggerdate | head -n 1)
          echo "FULL_IMAGE_NAME=$IMAGE_NAME:$LATEST_TAG" >> $GITHUB_ENV

      - name: Pull Image
        run: docker pull $FULL_IMAGE_NAME

      - name: Docker Image Info
        run: |
          docker image ls

      - name: Scan Image via Anchore Grype
        uses: anchore/scan-action@v6
        id: scan
        with:
          image: ${{ env.FULL_IMAGE_NAME }}
          fail-build: true
          severity-cutoff: high
          grype-version: v0.92.0
          output-format: table
